[package]
name = "vino-provider-cli"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ['cli']
reflection = ["tonic-reflection"]
cli = ['http', 'grpc', 'lattice']
http = ['vino-rpc', 'tonic/tls', 'vino-http', 'async-stream']
grpc = ['vino-rpc', 'tonic/tls', 'vino-invocation-server', 'async-stream']
lattice = ['vino-rpc', 'vino-lattice', 'async-stream']

[dependencies]
logger = { path = "../logger" }

vino-rpc = { path = "../vino-rpc", optional = true }
vino-invocation-server = { path = "../vino-invocation-server", optional = true }
vino-lattice = { path = "../vino-lattice", optional = true }
vino-http = { path = "../vino-http", optional = true }

vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }

cfg-if = "1.0"

tonic = { version = "0.6", optional = true }
tonic-reflection = { version = "0.3", default-features = false, optional = true }

tokio = { version = "1", features = [
  "macros",
  "fs",
  "net",
  "signal",
  "rt-multi-thread",
] }
tokio-stream = "0.1.6"
async-stream = { version = "0.3.2", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rand = "0.8"
tracing = "0.1"
thiserror = "1.0"
structopt = "0.3"
nkeys = { path = "../../../forks/nkeys" }

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
test-vino-provider = { path = "../../integration/test-vino-provider" }
once_cell = "1.8"
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"
serde_json = "1.0"
