[package]
name = "vino-codec"
version = "0.8.0"
edition = "2021"
license = "BSD-3-Clause"
description = "JSON, Messagepack, & Raw serde value encoding/decoding library"
documentation = "https://docs.vino.dev"
keywords = ["serde", "vino", "codec", "json", "messagepack"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["json", "messagepack"]
json = ["serde_json"]
messagepack = ["rmp-serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = { version = "0.15", optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = "1.0"
serde-value = "0.7.0"
