[package]
name = "test-interface-keyvalue"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "test-interface-collection"
path = "src/main.rs"

[dependencies]
thiserror = "1.0"
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-rpc = { path = "../../vino-rpc" }
vino-invocation-server = { path = "../../vino-invocation-server" }

tracing = "0.1"

maplit = "1.0"
anyhow = "1.0"
