version: 0
network:
  schematics:
    - name: logger
      instances:
        logger:
          id: vino::v0::log
      connections:
        - from:
            instance: <input>
            port: schem_input
          to:
            instance: logger
            port: log_input
        - from:
            instance: logger
            port: log_output
          to:
            instance: <output>
            port: schem_output
