[package]
name = "wick-xdg"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Cross-platform normalization for Wick libraries and binaries"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }
xdg = { workspace = true }

[dev-dependencies]
