[package]
name = "wick-xdg"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/candlecorp/wick"
description = "Cross-platform normalization for Wick libraries and binaries"
readme = "README.md"

[features]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
thiserror = { workspace = true }
getset = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
