[package]
name = "vino-packet"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"

[features]
default = ["wasm"]
wasm = []
native = []

[dependencies]
vino-codec = { path = "../vino-codec", features = ["messagepack"] }
serde = { version = "1.0.126", features = ["derive"] }
serde-value = "0.7.0"

[dev-dependencies]
env_logger = "0.9"
test-env-log = "0.2.7"
anyhow = "1.0.41"
log = "0.4"
