[package]
name = "vino-packet"
version = "0.7.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
repository = "https://github.com/vinodotdev/vino-sdk"
description = "Rust library encapsulating the message packets sent across Vino components."
documentation = "https://docs.vino.dev"
keywords = ["vino", "actor", "flow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://docs.vino.dev"


[features]
default = ["wasm"]
wasm = []
native = []

[dependencies]
vino-codec = { path = "../vino-codec", features = [
  "messagepack",
], version = "0.7.0" }
serde = { version = "1.0.126", features = ["derive"] }
serde-value = "0.7.0"

[dev-dependencies]
env_logger = "0.9"
test-env-log = "0.2.7"
anyhow = "1.0.41"
tracing = "0.1"
