[package]
name = "test-wasi-component"
version = "0.0.1"
description = ""
authors = [""]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["provider"]
provider = []
guest = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
wasmflow-sdk = { path = "../../../sdk/crates/wasmflow-sdk", features = ["v1"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
env_logger = "0.9"
test-log = "0.2"
