[package]
name = "wasm3-provider"
version = "0.0.3"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
exclude = [".assets"]
description = "A wasm3 engine provider for the waPC host"
license = "Apache-2.0"
homepage = "https://github.com/wapc/wasm3-provider"
documentation = "https://docs.rs/wasm3-provider"
readme = "README.md"
keywords = ["sdk", "wapc", "webassembly", "wasm", "wasm3"]
categories = ["wasm", "api-bindings"]

[dependencies]
wapc = { path = "../wapc-rust" }
wasm3 = { version = "0.1.3", features = ["build-bindgen"] }
log = "0.4.11"
