[package]
name = "wick-loader-utils"
version = "0.0.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-oci-utils = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
