[package]
name = "vino-runtime"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"

[features]

[dependencies]
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-macros = { path = "../../../sdk/crates/vino-macros" }
vino-manifest = { path = "../vino-manifest" }
vino-loader = { path = "../vino-loader" }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-wasm = { path = "../vino-provider-wasm" }
vino-provider-lattice = { path = "../vino-provider-lattice" }
vino-provider-par = { path = "../vino-provider-par" }
vino-provider-grpc = { path = "../vino-provider-grpc" }
vino-lattice = { path = "../vino-lattice" }
vino-native-api-0 = { path = "../../providers/provider-native-api-0" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-wascap = { path = "../vino-wascap" }
vino-rpc = { path = "../vino-rpc" }
vino-entity = { path = "../../../sdk/crates/vino-entity" }
vino-types = { path = "../../../sdk/crates/vino-types" }
vino-invocation-server = { path = "../vino-invocation-server" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

futures = "0.3"
async-trait = "0.1.50"
once_cell = "1.8"
parking_lot = { version = "0.11", features = [] }
thiserror = "1.0"
tokio = { version = "1", features = [
  "macros",
  "time",
  "sync",
  "rt-multi-thread",
] }
tokio-stream = { version = "0.1", features = [] }
itertools = "0.10"
tracing = "0.1"
dyn-clone = "1.0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
rand = { version = "0.8", default-features = false, features = [
  "std_rng",
  "alloc",
] }

[dev-dependencies]
test-vino-provider = { path = "../../integration/test-vino-provider" }
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
maplit = "1.0"
pretty_assertions = "1"
lazy_static = "1.4"
anyhow = "1.0"
runtime-testutils = { path = "./tests/runtime_utils" }
