[package]
name = "vino-provider-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
vino-rpc = { path = "../vino-rpc", features = ["client"] }
vino-transport = { path = "../../../sdk/crates/vino-transport" }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
parking_lot = "0.12"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1", features = ["process"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
http = "0.2"

[dev-dependencies]
vino-invocation-server = { path = "../../vino/vino-invocation-server" }
test-vino-provider = { path = "../../integration/test-vino-provider" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { version = "1", features = ["macros"] }
tokio-stream = "0.1.7"
anyhow = "1.0"
