[package]
name = "vino-provider-par"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
vino-par = { path = "../vino-par" }
vino-loader = { path = "../vino-loader" }
vino-rpc = { path = "../vino-rpc", features = ["client"] }
vino-transport = { path = "../../../sdk/crates/vino-transport" }
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-cli = { path = "../vino-provider-cli", default-features = false }
parking_lot = "0.12"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1"
tar = "0.4"
tokio = { version = "1", features = ["process"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shellexpand = "2.1"

[dev-dependencies]
test-vino-provider = { path = "../../integration/test-vino-provider" }
test-logger = { path = "../../misc/test-logger" }
logger = { path = "../logger" }
tokio = { version = "1", features = ["macros"] }
tokio-stream = "0.1.7"
anyhow = "1.0"
vino-wascap = { path = "../vino-wascap" }
workspace-root = { path = "../../misc/workspace-root" }
