[package]
name = "wasmflow-packet"
version = "0.9.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/vinodotdev/vino-sdk"
description = "Rust library encapsulating the message packets sent across Vino components."
documentation = "https://docs.vino.dev"
keywords = ["vino", "actor", "flow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://docs.vino.dev"


[features]
default = []
all = ["v0"]
v0 = []


[dependencies]
wasmflow-codec = { path = "../wasmflow-codec", features = [], version = "0.9.0" }
serde = { version = "1.0", features = ["derive"] }
serde-value = "0.7"

[dev-dependencies]
env_logger = "0.9"
test-log = "0.2"
anyhow = "1.0"
tracing = "0.1"
