[package]
name = "flow-graph-interpreter"
version = "0.20.0"
edition = "2021"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wasmrs = { workspace = true }
wasmrs-rx = { workspace = true }
wasmrs-frames = { workspace = true }
wasmrs-codec = { workspace = true }
wick-packet = { workspace = true }
flow-graph = { workspace = true }
wick-config = { workspace = true }
flow-expression-parser = { workspace = true }
wick-interface-types = { workspace = true }
seeded-random = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }
performance-mark = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "macros"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
parking_lot = { workspace = true }
serde_json = { workspace = true }
serde-value = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rand = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
logger = { workspace = true }
test-logger = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
rot = { workspace = true }
