[package]
name = "wasmflow-codec"
version = "0.10.0"
edition = "2021"
license = "Apache-2.0"
description = "JSON, Messagepack, & Raw serde value encoding/decoding library"
documentation = "https://wasmflow.com"
keywords = ["serde", "wasmflow", "codec", "json", "messagepack"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = { version = "1.1.0" }
serde_json = { version = "1.0" }
thiserror = "1.0"
serde-value = "0.7.0"
