[package]
name = "wasmflow-transport"
version = "0.10.0-beta.2"
edition = "2021"
license = "BSD-3-Clause"
description = "Transport layer for Wasmflow packets"
documentation = "https://wasmflow.com"
keywords = ["serde", "wasmflow", "packet", "transport"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
all = ["async"]
wasm = []
async = ["tokio", "tokio-stream", "parking_lot"]

[dependencies]
wasmflow-packet = { path = "../wasmflow-packet", version = "0.9.0", features = [
  "v0",
] }
wasmflow-codec = { path = "../wasmflow-codec", version = "0.10.0-beta.2" }
wasmflow-macros = { path = "../wasmflow-macros", version = "0.10.0-beta.2" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"

# raw
serde-value = { version = "0.7" }

# json
serde_json = { version = "1.0" }

# async
tokio = { version = "1", features = [], optional = true }
tokio-stream = { version = "0.1", optional = true }
parking_lot = { version = "0.12", optional = true }

[dev-dependencies]
test-log = "0.2.8"
anyhow = "1.0"
env_logger = "0.9"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
