[package]
name = "vino-types"
version = "0.1.0"
edition = "2018"
license = "BSD-3-Clause"
description = "Types used by the Vino tool chain"
documentation = "https://docs.vino.dev"
keywords = ["types", "vino"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
