[package]
name = "wasmflow-interface"
version = "0.9.0"
edition = "2021"
license = "BSD-3-Clause"
description = "Types used by the Vino tool chain"
documentation = "https://docs.vino.dev"
keywords = ["types", "vino"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasmflow-macros = { path = "../wasmflow-macros", version = "0.9.0" }

[dev-dependencies]
anyhow = "1.0"
test-log = "0.2.8"
env_logger = "0.9"
pretty_assertions = "1.2"
serde_json = "1.0"
