[package]
name = "wick-cli"
version = "0.7.0"
edition = "2021"
default-run = "wick"
license = "Elastic-2.0"
repository = "https://github.com/candlecorp/wick"
description = "The binary executable for the Wick project."

[features]
default = []
cross = ["openssl/vendored"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-xdg = { workspace = true }
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
wick-rpc = { workspace = true, features = ["client"] }
wick-component-cli = { workspace = true }
wick-host = { workspace = true }
wick-config = { workspace = true }
wick-test = { workspace = true }
wick-wascap = { workspace = true }
wick-oci-utils = { workspace = true }
wick-package = { workspace = true }
wick-logger = { workspace = true }
seeded-random = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nkeys = { workspace = true }
atty = { workspace = true }
jaq-core = { workspace = true }
markup-converter = { workspace = true }
openssl = { workspace = true, features = ["vendored"], optional = true }

[dev-dependencies]
test_bin = { workspace = true }
trycmd = { workspace = true }
test-logger = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true, features = ["process"] }
rstest = { workspace = true }

[[bin]]
name = "wick"
path = "src/main.rs"
