[package]
name = "wick"
version = "0.5.0"
edition = "2021"
default-run = "wick"
license = "Elastic-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wick-packet = { workspace = true }
wick-interface-types = { workspace = true }
wick-rpc = { workspace = true, features = ["client"] }
wick-loader-utils = { workspace = true }
wick-component-wasm = { workspace = true }
wick-component-cli = { workspace = true }
wick-runtime = { workspace = true }
wick-host = { workspace = true }
wick-config = { workspace = true }
wick-test = { workspace = true }
wick-wascap = { workspace = true }
wick-oci-utils = { workspace = true }
wick-grpctar = { workspace = true }
logger = { workspace = true }
seeded-random = { workspace = true }
tap = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true, features = ["derive"] }
nkeys = "0.2"
atty = "0.2"
jaq-core = "0.9"
markup-converter = "0.2"
oci-distribution = { version = "0.9", features = [
  "rustls-tls",
], default-features = false }
async-recursion = { workspace = true }
openssl = { version = "0.10" } #required for cross compilation (don't remove)

[dev-dependencies]
test_bin = "0.4"
trycmd = "0.14"
test-logger = { workspace = true }
tokio-test-bin = { workspace = true }
regex = { workspace = true }

[[bin]]
name = "wick"
path = "src/main.rs"
