[package]
name = "vino-entity"
version = "0.7.0"
edition = "2021"
license = "BSD-3-Clause"
description = "Entities found in a Vino network"
documentation = "https://docs.vino.dev"
keywords = ["vino", "flow"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
vino-macros = { path = "../vino-macros", version = "0.7.0" }
serde = { version = "1.0.118", features = ["derive"] }
thiserror = "1.0.25"
url = "2.2.2"

[dev-dependencies]
pretty_assertions = "1.0.0"
