[package]
name = "vino-provider"
version = "0.7.0"
edition = "2021"
license = "BSD-3-Clause"
description = "SDK for native and WASM Vino components"
documentation = "https://docs.vino.dev"
keywords = ["wasm", "vino", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
wasm = ["vino-transport/wasm", "vino-types", "vino-wapc/guest"]
signatures = []
native = [
  "thiserror",
  "async-trait",
  "tokio",
  "tokio-stream",
  "tracing",
  "vino-transport/all",
  "vino-types",
  "dyn-clone",
]
host = ["vino-wapc"]

[dependencies]
vino-packet = { path = "../vino-packet", version = "0.7.0" }
vino-wapc = { path = "../vino-wapc", version = "0.7.0", optional = true }
vino-entity = { path = "../vino-entity", version = "0.7.0" }
vino-codec = { path = "../vino-codec", version = "0.7.0" }
serde = { version = "1.0", features = ["derive"] }

vino-transport = { path = "../vino-transport", version = "0.7.0", optional = true }

# For native providers
vino-types = { path = "../vino-types", version = "0.7.0", optional = true }
async-trait = { version = "0.1", optional = true }
thiserror = { version = "1.0", optional = true }
tokio = { version = "1", features = [], optional = true }
tokio-stream = { version = "0.1", features = [], optional = true }
tracing = { version = "0.1", optional = true }
dyn-clone = { version = "1.0", optional = true }

[dev-dependencies]
env_logger = "0.9"
test-env-log = "0.2.7"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
