[package]
name = "vino-provider"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-transport = { path="../vino-transport" }
vino-rpc = { path="../vino-rpc" }
vino-guest = { path="../vino-guest" }
serde = { version="1.0.118", features=["derive"] }
futures = "0.3.15"
async-trait = "0.1.50"
thiserror = "1.0.25"
rmp-serde = "0.15.5"

[dev-dependencies]
env_logger = "0.8.4"
test-env-log = "0.2.7"
tokio = { version="1.4.0", features=["macros", "rt-multi-thread"] }
