[package]
name = "vino-keyvalue-redis"
version = "0.0.0"
edition = "2021"

[features]
test-integration = []


[dependencies]
vino-provider = { path = "../../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-provider-cli = { path = "../../vino/vino-provider-cli" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-rpc = { path = "../../vino/vino-rpc" }
vino-macros = { path = "../../../sdk/crates/vino-macros" }
vino-interface-keyvalue = { path = "../../interfaces/interface-keyvalue", features = [
  "native",
  "provider",
  "guest",
] }
redis = { version = "0.21", features = ["tokio-comp"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.50"
futures = "0.3"
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread"] }
once_cell = "1.8"
tokio-util = { version = "0.6", features = ["codec"] }
structopt = "0.3"
tracing = "0.1"

[dev-dependencies]
logger = { path = "../../vino/logger" }
serde_json = "1.0"
tonic = "0.6"
rand = "0.8"
anyhow = "1.0"
test-logger = { path = "../../misc/test-logger" }
