[package]
name = "vino-macros"
version = "0.7.0"
edition = "2018"
license = "BSD-3-Clause"
description = "Macros use by vino tools"
documentation = "https://docs.vino.dev"
keywords = ["macros", "vino"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
tracing = "0.1"
lazy_static = "1.4.0"
