[package]
name = "vino-macros"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
vino-transport = { path = "../vino-transport" }
colored = "2.0.0"
log = "0.4"
lazy_static = "1.4.0"
