[package]
name = "vino-random"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8" }
rand_chacha = "0.3"
parking_lot = "0.12"
uuid = { version = "1.1", features = ["v4"] }
