[package]
name = "wasmflow-component"
version = "0.9.0"
edition = "2021"
license = "BSD-3-Clause"
description = "WaPC-related functions for Wasmflow"
documentation = "https://wasmflow.com"
keywords = ["wapc", "wasmflow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/wasmflow/wasmflow-sdk"
homepage = "https://wasmflow.com"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
guest = []
v1 = ["wasmflow-boundary/v1"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
yielding-executor = { version = "0.10.0", features = [] }
tokio = { version = "1", features = ["sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wasmflow-invocation = { path = "../wasmflow-invocation", version = "0.9.0" }

[dependencies]
cfg-if = "1.0.0"
wasmflow-codec = { path = "../wasmflow-codec", version = "0.9.0", features = [
] }
wasmflow-streams = { path = "../wasmflow-streams", version = "0.9.0", features = [
] }
wasmflow-boundary = { path = "../wasmflow-boundary", version = "0.9.0", features = [
] }
wasmflow-transport = { path = "../wasmflow-transport", version = "0.9.0", features = [
] }
wasmflow-packet = { path = "../wasmflow-packet", version = "0.9.0" }
serde = { version = "1.0", features = ["derive"] }
