[package]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "BSD-3-Clause"
name = "vino-manifest"
version = "0.1.0"

[dependencies]
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }

lazy_static = "1.4"
num-traits = "0.2"
regex = "1"
serde = "1.0"
serde-value = "0.7"
serde-with-expand-env = "1.1"
serde_json = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tracing = "0.1"
wasmflow-macros = { path = "../../../sdk/crates/wasmflow-macros" }
shellexpand = "2.1"

[dev-dependencies]
anyhow = "1.0"

pretty_assertions = "1"
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
