[package]
name = "vino-codec"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.118", features=["derive"] }
rmp-serde = "0.15.4"
thiserror = "1.0.25"
