[package]
name = "vinoc"
version = "0.3.2"
edition = "2021"
default-run = "vinoc"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-par = { path = "../../vino/vino-par" }
vino-runtime = { path = "../../vino/vino-runtime" }
vino-packet = { path = "../../../sdk/crates/vino-packet" }
vino-host = { path = "../../vino/vino-host" }
vino-provider-cli = { path = "../../vino/vino-provider-cli" }
vino-manifest = { path = "../../vino/vino-manifest" }
vino-rpc = { path = "../../vino/vino-rpc", features = ["client"] }
vino-wascap = { path = "../../vino/vino-wascap" }
logger = { path = "../../vino/logger" }
vino-codec = { path = "../../../sdk/crates/vino-codec" }
vino-macros = { path = "../../../sdk/crates/vino-macros" }
vino-entity = { path = "../../../sdk/crates/vino-entity" }
vino-types = { path = "../../../sdk/crates/vino-types" }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }

async-recursion = "1.0"
nkeys = { path = "../../../forks/nkeys" }
tracing = "0.1"
clap = { version = "3.0", features = ["derive", "env"] }
futures = "0.3"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = [
  "macros",
  "signal",
  "io-std",
  "rt-multi-thread",
  "io-util",
] }
tonic = { version = "0.6", features = ["tls"] }
atty = "0.2"
oci-distribution = { path = "../../../forks/oci-distribution", features = [
  "rustls-tls",
], default-features = false }
vino-oci = { path = "../../vino/vino-oci" }

[[bin]]
name = "vinoc"
path = "src/main.rs"
