[package]
name = "vino-provider-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmtime"]
wasmtime = ["wasmtime-provider"]
# wasm3 = ["wasm3-provider"]

[dependencies]
vino-rpc = { path = "../vino-rpc" }
vino-random = { path = "../vino-random" }
vino-wascap = { path = "../vino-wascap" }
vino-loader = { path = "../vino-loader" }
wasmflow-packet = { path = "../../../sdk/crates/wasmflow-packet" }
wasmflow-entity = { path = "../../../sdk/crates/wasmflow-entity" }
wasmflow-codec = { path = "../../../sdk/crates/wasmflow-codec" }
wasmflow-output = { path = "../../../sdk/crates/wasmflow-output", features = [] }
vino-transport = { path = "../../../sdk/crates/vino-transport", features = [
  "all",
] }
wasmflow-sdk = { path = "../../../sdk/crates/wasmflow-sdk", features = ["v1"] }
wasmflow-interface = { path = "../../../sdk/crates/wasmflow-interface" }
wasmflow-component = { path = "../../../sdk/crates/wasmflow-component" }
wasmflow-invocation = { path = "../../../sdk/crates/wasmflow-invocation" }
wasmflow-collection-link = { path = "../../../sdk/crates/wasmflow-collection-link" }
wasmflow-macros = { path = "../../../sdk/crates/wasmflow-macros" }
derivative = "2.2"
tokio = { version = "1", features = ["fs"] }
parking_lot = "0.12"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-value = "0.7"

# wasmtime-provider = { version = "1.0", optional = true, features = ["cache"] }
# wapc = "1.0"
# wapc-pool = "1.0"
wasmtime-provider = { git = "https://github.com/vinodotdev/wapc-rs", branch = "master", optional = true, features = [
  "cache",
] }
wapc = { git = "https://github.com/vinodotdev/wapc-rs", branch = "master" }
wapc-pool = { git = "https://github.com/vinodotdev/wapc-rs", branch = "master" }


tokio-stream = "0.1.7"
async-stream = "0.3.2"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1.50"

[dev-dependencies]
logger = { path = "../logger" }
test-logger = { path = "../../misc/test-logger" }
futures = "0.3"
anyhow = "1.0"
