[package]
name = "vino-rpc"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["tokio/fs"]

[dependencies]
vino-packet = { path = "../../sdk/crates/vino-packet" }
vino-codec = { path = "../../sdk/crates/vino-codec" }
vino-entity = { path = "../../sdk/crates/vino-entity" }
vino-transport = { path = "../../sdk/crates/vino-transport", features = [
  "all",
] }
vino-types = { path = "../../sdk/crates/vino-types" }
vino-provider = { path = "../../sdk/crates/vino-provider", features = [
  "native",
] }
vino-macros = { path = "../../sdk/crates/vino-macros" }

tonic = { version = "0.6", features = ["tls"] }
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-stream = "0.3.2"
rand = "0.8"
tracing = "0.1"
thiserror = "1.0"
async-trait = "0.1.50"
dyn-clone = "1.0.4"

[build-dependencies]
tonic-build = { version = "0.6", default-features = false, features = [
  "prost",
  "transport",
] }

[dev-dependencies]
