---
version: 0
network:
  providers:
    - namespace: test-namespace
      kind: GrpcUrl
      reference: https://127.0.0.1:$TEST_PORT
  schematics:
    - name: grpc
      providers:
        - test-namespace
      instances:
        external:
          id: test-namespace::test-component
      connections:
        - <> => external[input]
        - external[output] => <>
