[package]
name = "vino-transport"
version = "0.6.2"
edition = "2018"
license = "BSD-3-Clause"
description = "Transport layer for Vino packets"
documentation = "https://docs.vino.dev"
keywords = ["serde", "vino", "packet", "transport"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
vino-packet = { path = "../vino-packet", version = "=0.6.2" }
vino-codec = { path = "../vino-codec", version = "=0.6.2" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.25"
log = "0.4.14"
serde-value = "0.7.0"
tokio-stream = { version = "0.1.6" }
tokio = { version = "1.4.0", features = [] }
lazy_static = "1.4.0"

[dev-dependencies]
test-env-log = "0.2.7"
env_logger = "0.9.0"
log = "0.4"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "macros"] }
