name: builder-builder
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/builder.yaml
      - docker/Dockerfile.builder

jobs:
  build:
    # add permission to write packages
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/candlecorp/wick-builder:${{ steps.prep.outputs.BUILD_ID }}, ghcr.io/candlecorp/wick-builder:latest
          registry: ghcr.io
          file: docker/Dockerfile.builder
          build-args: |
            CONTAINER=${{ secrets.SCCACHE_AZURE_BLOB_CONTAINER }}
            CONTAINER_CONN_STRING=${{ secrets.SCCACHE_AZURE_CONNECTION_STRING }}
            CACHE_KEY_PREFIX=wick
          push: true
